
status = warn
name = ProgregSecLogging

property.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{1.} - %m%n

appenders = console

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = ${pattern}

logger.sec.name = org.springframework.security
logger.sec.level = ALL

logger.progreg.name = com.progreg
logger.progreg.level = ALL

rootLogger.level = info
rootLogger.appenderRefs = console, rolling
rootLogger.appenderRef.console.ref = CONSOLE